baseURL = 'https://username.github.io/skorikov-gallery'
[languages]
  [languages.ru]
    languageCode = 'ru-ru'
    languageName = 'Русский'
    title = 'Скориков Игорь Андреевич - Галерея'
    weight = 1

  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    title = 'Skorikov Igor Andreevich - Gallery'
    weight = 2
theme = 'gallery'

[params]
  artist_name = "Скориков Игорь Андреевич"
  artist_title = "Художник"
  artist_desk = "Член союза художников России"
  vk = "https://vk.com/igorandreev12345"
  email = "skorikov.igor@gmail.com"
  telegram = "@Igor_Skorikov"
  facebook = "https://www.facebook.com/profile.php?id=100063819441557"

[imaging]
  quality = 85
  resampleFilter = "lanczos"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
