baseURL = 'https://username.github.io/skorikov-gallery'
defaultContentLanguage = 'ru'
theme = 'gallery'

[languages]
  [languages.ru]
    languageCode = 'ru-ru'
    languageName = 'Русский'
    title = 'Скориков Игорь Андреевич - Галерея'
    weight = 1
    [languages.ru.params]
      artist_name = "Скориков Игорь Андреевич"
      artist_title = "Художник"
      artist_desk = "Член союза художников России"
      vk = "https://vk.com/igorandreev12345"
      email = "skorikov.igor@gmail.com"
      telegram = "@Igor_Skorikov"
      facebook = "https://www.facebook.com/profile.php?id=100063819441557"
      footer_text = "Искусство вечно"
      no_images_text = "Изображения не найдены. Поместите изображения в папку"
      painting_alt = "Картина"
      qr_alt = "QR код"
      phone_alt = "Телефон"
      brush_alt = "Кисть художника"
      copyright_text = "© %s %s"
      
  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    title = 'Igor Skorikov - Gallery'
    weight = 2
    [languages.en.params]
      artist_name = "Igor Andreevich Skorikov"
      artist_title = "Artist"
      artist_desk = "Member of the Union of Artists of Russia"
      vk = "https://vk.com/igorandreev12345"
      email = "skorikov.igor@gmail.com"
      telegram = "@Igor_Skorikov"
      facebook = "https://www.facebook.com/profile.php?id=100063819441557"
      footer_text = "Art is eternal"
      no_images_text = "No images found. Place images in the folder"
      painting_alt = "Painting"
      qr_alt = "QR code"
      phone_alt = "Phone"
      brush_alt = "Artist's brush"
      copyright_text = "© %s %s"

[imaging]
  quality = 85
  resampleFilter = "lanczos"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
