name: Deploy Skorikov Gallery to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false



defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Hugo CLI
        run: |
          wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i /tmp/hugo.deb
          hugo version

      - name: Build site with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --gc --minify --baseURL "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

      - name: Deploy to GitHub Pages
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Configure remote URL with token
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # Create gh-pages branch if it doesn't exist
          git checkout --orphan gh-pages

          # Remove all files except public
          find . -maxdepth 1 ! -name 'public' ! -name '.git' ! -name '.' -exec rm -rf {} + 2>/dev/null || true

          # Move contents of public to root
          if [ -d "public" ]; then
            mv public/* . 2>/dev/null || true
            mv public/.* . 2>/dev/null || true
            rmdir public 2>/dev/null || true
          fi

          # Create .nojekyll file
          touch .nojekyll

          # Add and commit
          git add -A
          git commit -m "Deploy site - $(date)" || exit 0

          # Push to gh-pages branch
          git push --force origin gh-pages
